version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ../Dockerfile-composer.dockerfile
    container_name: symfony_app
    volumes:
      - .:/var/www/symfony:delegated
      - /var/www/symfony/var
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql://symfony:password@db:3306/symfony?serverVersion=mariadb-10.5.0"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
      
    volumes:
      - /var/lib/postgresql/data